### ISSUE TITLE
Client original IP address and docker-proxy

### ISSUE THREAD

**Issue by hroost** [TeamSpeak-Systems/ts-services#13]
Hello,

I found this strange behavior with the client's original IP address and docker-proxy.
Using default docker-compose example with
```
services:
  teamspeak:
    image: teamspeaksystems/teamspeak_server:58rc12
    expose:
      - "9987:9987/udp"
    ports:
      - "9987:9987/udp"
```
after a successful connection to the server in server logs and client's Connection Info I'm seeing my original IP.
Then let's do a server restart via `docker-compose restart teamspeak` and wait till TS client will perform auto reconnecting. Then check IP again - now it's internal docker 172.18.0.1 instead of the real one. Restart TS client and it's again real IP.
Btw, sometimes docker-compose restart goes smoothly (faster?) and I'm seeing real IP. In this case, trying something like that `docker-compose stop teamspeak && sleep 10 && docker-compose start teamspeak` helps to reproduce

TS client 5.0.0-beta71 macOS

I would appreciate any suggestions how to workaround this (ideally without network_mode: host)
